services:
  postgres:
    image: postgres:16
    container_name: nexstore_db
    restart: unless-stopped
    ports:
      - '${POSTGRES_PORT:-5002}:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-nexstore}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-nexstore}
      POSTGRES_DB: ${POSTGRES_DB:-nexstore}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-nexstore} -d ${POSTGRES_DB:-nexstore}']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: nexstore_redis
    restart: unless-stopped
    ports:
      - '${REDIS_PORT:-5003}:6379'
    volumes:
      - redis_data:/var/lib/redis/data

  minio:
    image: minio/minio:latest
    container_name: nexstore_minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${STORAGE_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${STORAGE_SECRET_KEY:-minioadmin}
    command: server /data --console-address ':9001'
    ports:
      - '${MINIO_PORT:-5004}:9000'
      - '${MINIO_CONSOLE_PORT:-5005}:9001'
    volumes:
      - minio_data:/data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 10s
      timeout: 5s
      retries: 5

  minio-init:
    image: minio/mc:latest
    container_name: nexstore_minio_init
    depends_on:
      minio:
        condition: service_healthy
    restart: 'no'
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 ${STORAGE_ACCESS_KEY:-minioadmin} ${STORAGE_SECRET_KEY:-minioadmin};
      mc mb --ignore-existing local/${STORAGE_BUCKET:-nexstore-products};
      mc anonymous set public local/${STORAGE_BUCKET:-nexstore-products};
      "

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: nexstore_back
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      minio-init:
        condition: service_completed_successfully
      redis:
        condition: service_started
    env_file:
      - .env
    environment:
      PORT: 5001
      DATABASE_URL: postgresql://${POSTGRES_USER:-nexstore}:${POSTGRES_PASSWORD:-nexstore}@postgres:5432/${POSTGRES_DB:-nexstore}?schema=public
      CORS_ORIGIN: ${FRONTEND_ORIGIN:-http://localhost:5000}
      JWT_SECRET: ${JWT_SECRET:-11f5a3ee55273d281c78c1329e73c52e37c359b19a0ebc36338904fb78ebb0f06dca1422b53d7fa1ececc4c2ed622e53edf3587d4f67e18a4c89250f8d3372ba}
      JWT_ACCESS_TTL: ${JWT_ACCESS_TTL:-15m}
      JWT_REFRESH_TTL: ${JWT_REFRESH_TTL:-7d}
      STORAGE_PROVIDER: ${STORAGE_PROVIDER:-minio}
      STORAGE_BUCKET: ${STORAGE_BUCKET:-nexstore-products}
      STORAGE_REGION: ${STORAGE_REGION:-us-east-1}
      STORAGE_ENDPOINT: ${STORAGE_ENDPOINT:-http://minio:9000}
      STORAGE_ACCESS_KEY: ${STORAGE_ACCESS_KEY:-minioadmin}
      STORAGE_SECRET_KEY: ${STORAGE_SECRET_KEY:-minioadmin}
      STORAGE_PUBLIC_URL: ${STORAGE_PUBLIC_URL:-http://localhost:5004/nexstore-products}
      STORAGE_FORCE_PATH_STYLE: ${STORAGE_FORCE_PATH_STYLE:-true}
      STORAGE_MAX_FILE_SIZE_BYTES: ${STORAGE_MAX_FILE_SIZE_BYTES:-5242880}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}
    ports:
      - '5001:5001'
    healthcheck:
      test: ['CMD-SHELL', 'wget --spider -q http://127.0.0.1:5001/api/health || exit 1']
      interval: 15s
      timeout: 5s
      retries: 10

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: nexstore_front
    restart: unless-stopped
    depends_on:
      back:
        condition: service_healthy
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:5001/api}
      INTERNAL_API_URL: http://back:5001/api/v1
    ports:
      - '5000:5000'

volumes:
  pg_data:
  minio_data:
  redis_data:
