services:
  postgres:
    image: postgres:16
    container_name: nexstore_db
    restart: unless-stopped
    ports:
      - '${DATABASE_PORT:-5008}:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-nexstore}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-nexstore}
      POSTGRES_DB: ${POSTGRES_DB:-nexstore}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-nexstore} -d ${POSTGRES_DB:-nexstore}']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: nexstore_redis
    restart: unless-stopped
    ports:
      - '${REDIS_PORT:-5009}:6379'
    volumes:
      - redis_data:/data

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: nexstore_back
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    environment:
      PORT: 5007
      DATABASE_URL: postgresql://${POSTGRES_USER:-nexstore}:${POSTGRES_PASSWORD:-nexstore}@postgres:5432/${POSTGRES_DB:-nexstore}?schema=public
      CORS_ORIGIN: ${FRONTEND_ORIGIN:-http://localhost:5006}
      JWT_SECRET: ${JWT_SECRET:-11f5a3ee55273d281c78c1329e73c52e37c359b19a0ebc36338904fb78ebb0f06dca1422b53d7fa1ececc4c2ed622e53edf3587d4f67e18a4c89250f8d3372ba}
      JWT_ACCESS_TTL: ${JWT_ACCESS_TTL:-15m}
      JWT_REFRESH_TTL: ${JWT_REFRESH_TTL:-7d}
      STORAGE_PROVIDER: r2
      STORAGE_BUCKET: ${STORAGE_BUCKET:-nexstore-products}
      STORAGE_REGION: ${STORAGE_REGION:-auto}
      STORAGE_ENDPOINT: ${STORAGE_ENDPOINT:-}
      STORAGE_ACCESS_KEY: ${STORAGE_ACCESS_KEY:-}
      STORAGE_SECRET_KEY: ${STORAGE_SECRET_KEY:-}
      STORAGE_PUBLIC_URL: ${STORAGE_PUBLIC_URL:-}
      STORAGE_MAX_FILE_SIZE_BYTES: ${STORAGE_MAX_FILE_SIZE_BYTES:-5242880}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}
    ports:
      - '5007:5007'
    healthcheck:
      test: ['CMD-SHELL', 'wget --spider -q http://127.0.0.1:5007/api/health || exit 1']
      interval: 15s
      timeout: 5s
      retries: 10

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: nexstore_front
    restart: unless-stopped
    depends_on:
      back:
        condition: service_healthy
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:5007/api}
      INTERNAL_API_URL: http://back:5007/api/v1
    ports:
      - '5006:5006'

volumes:
  pg_data:
  redis_data:
