services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
      target: builder
    command: sh -c "npx prisma db push --skip-generate && npm run start:dev"
    environment:
      PORT: 5007
      CHOKIDAR_USEPOLLING: "true"
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}
      # Real secret fallback para validación local rápida
      JWT_SECRET: ${JWT_SECRET:-11f5a3ee55273d281c78c1329e73c52e37c359b19a0ebc36338904fb78ebb0f06dca1422b53d7fa1ececc4c2ed622e53edf3587d4f67e18a4c89250f8d3372ba}
      JWT_ACCESS_TTL: ${JWT_ACCESS_TTL:-15m}
      JWT_REFRESH_TTL: ${JWT_REFRESH_TTL:-7d}
      TAX_RATE: ${TAX_RATE:-0.15}
    healthcheck:
      disable: true
    volumes:
      - ./back:/app
      - back_node_modules:/app/node_modules
    ports:
      - '5007:5007'

  redis:
    image: redis:7-alpine
    container_name: nexstore_redis
    restart: unless-stopped
    ports:
      - '${REDIS_PORT:-5009}:6379'

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
      target: deps
    command: sh -c "npm install && npm run dev -- --webpack --hostname 0.0.0.0 --port 5006"
    environment:
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:5007/api}
    depends_on:
      - back
    volumes:
      - ./front:/app
      - front_node_modules:/app/node_modules
      - front_next_cache:/app/.next
    ports:
      - '5006:5006'

volumes:
  back_node_modules:
  front_node_modules:
  front_next_cache:
