#!/bin/bash
# Script para refactorizar use cases restantes que dependen de AdminService
# Este script muestra el patrón a seguir para cada tipo de use case

echo "=========================================="
echo "Refactorización de Admin Use Cases"
echo "=========================================="
echo ""
echo "Use cases pendientes de refactorizar:"
echo ""

# Lista de use cases pendientes
PENDING_USE_CASES=(
  "update-user-status.use-case.ts:ADMIN_USER_REPOSITORY:AdminUserRepositoryPort"
  "update-user-role.use-case.ts:ADMIN_USER_REPOSITORY:AdminUserRepositoryPort,ADMIN_AUDIT_REPOSITORY:AdminAuditRepositoryPort"
  "update-product-status.use-case.ts:ADMIN_PRODUCT_REPOSITORY:AdminProductRepositoryPort"
  "update-payment-status.use-case.ts:ADMIN_ORDER_REPOSITORY:AdminOrderRepositoryPort"
  "update-order-notes.use-case.ts:ADMIN_ORDER_REPOSITORY:AdminOrderRepositoryPort"
  "update-country.use-case.ts:ADMIN_COUNTRY_REPOSITORY:AdminCountryRepositoryPort"
  "update-category.use-case.ts:ADMIN_CATEGORY_REPOSITORY:AdminCategoryRepositoryPort"
  "get-user-by-id.use-case.ts:ADMIN_USER_REPOSITORY:AdminUserRepositoryPort"
  "get-top-products.use-case.ts:ADMIN_METRICS_REPOSITORY:AdminMetricsRepositoryPort"
  "get-sales-chart.use-case.ts:ADMIN_METRICS_REPOSITORY:AdminMetricsRepositoryPort"
  "get-recent-orders.use-case.ts:ADMIN_METRICS_REPOSITORY:AdminMetricsRepositoryPort"
  "get-product-by-id.use-case.ts:ADMIN_PRODUCT_REPOSITORY:AdminProductRepositoryPort"
  "get-order-by-id.use-case.ts:ADMIN_ORDER_REPOSITORY:AdminOrderRepositoryPort"
  "get-countries.use-case.ts:ADMIN_COUNTRY_REPOSITORY:AdminCountryRepositoryPort"
  "get-category-by-id.use-case.ts:ADMIN_CATEGORY_REPOSITORY:AdminCategoryRepositoryPort"
  "delete-user.use-case.ts:ADMIN_USER_REPOSITORY:AdminUserRepositoryPort,ADMIN_AUDIT_REPOSITORY:AdminAuditRepositoryPort"
  "delete-country.use-case.ts:ADMIN_COUNTRY_REPOSITORY:AdminCountryRepositoryPort"
  "delete-category.use-case.ts:ADMIN_CATEGORY_REPOSITORY:AdminCategoryRepositoryPort"
  "create-country.use-case.ts:ADMIN_COUNTRY_REPOSITORY:AdminCountryRepositoryPort"
)

echo "Total: ${#PENDING_USE_CASES[@]} use cases"
echo ""
echo "Patrón de refactorización:"
echo "-------------------------"
echo ""
echo "1. Reemplazar la importación de AdminService por los puertos necesarios:"
echo "   ANTES:"
echo "   import { AdminService } from '../admin.service';"
echo ""
echo "   DESPUÉS:"
echo "   import { ADMIN_USER_REPOSITORY, type AdminUserRepositoryPort } from '../../domain/ports/admin-user.repository.port';"
echo ""
echo "2. Reemplazar el constructor:"
echo "   ANTES:"
echo "   constructor(@Inject(AdminService) private readonly adminService: AdminService) {}"
echo ""
echo "   DESPUÉS:"
echo "   constructor("
echo "     @Inject(ADMIN_USER_REPOSITORY) private readonly userRepository: AdminUserRepositoryPort,"
echo "   ) {}"
echo ""
echo "3. Mover la lógica de negocio desde AdminService al use case:"
echo "   ANTES:"
echo "   execute(userId: string, isActive: boolean, actorId: string, actorRole: Role) {"
echo "     return this.adminService.updateUserStatus(userId, isActive, actorId, actorRole);"
echo "   }"
echo ""
echo "   DESPUÉS:"
echo "   async execute(userId: string, isActive: boolean, actorId: string, actorRole: Role) {"
echo "     if (userId === actorId) {"
echo "       throw new BadRequestError('You cannot change your own status');"
echo "     }"
echo "     await this.assertCanManageTargetUser(userId, actorRole);"
echo "     return this.userRepository.updateStatus(userId, isActive);"
echo "   }"
echo ""
echo "4. Agregar imports necesarios para errores de dominio:"
echo "   import { BadRequestError, NotFoundError, ForbiddenError, ConflictError } from '../../../../shared/domain/errors/domain-error';"
echo ""
echo "Lista de puertos disponibles:"
echo "---------------------------"
echo "- ADMIN_METRICS_REPOSITORY / AdminMetricsRepositoryPort"
echo "- ADMIN_USER_REPOSITORY / AdminUserRepositoryPort"
echo "- ADMIN_ORDER_REPOSITORY / AdminOrderRepositoryPort"
echo "- ADMIN_PRODUCT_REPOSITORY / AdminProductRepositoryPort"
echo "- ADMIN_CATEGORY_REPOSITORY / AdminCategoryRepositoryPort"
echo "- ADMIN_COUNTRY_REPOSITORY / AdminCountryRepositoryPort"
echo "- ADMIN_AUDIT_REPOSITORY / AdminAuditRepositoryPort"
echo "- ADMIN_PRODUCT_IMAGE_REPOSITORY / AdminProductImageRepositoryPort"
echo ""
echo "Ejemplo completo en:"
echo "- src/modules/admin/application/use-cases/update-product.use-case.ts"
echo "- src/modules/admin/application/use-cases/create-product.use-case.ts"
echo "- src/modules/admin/application/use-cases/delete-product.use-case.ts"
echo ""
